### ISSUE TITLE
change in storage location not reflected in GUI after using filepath command 

### ISSUE THREAD

**Issue by Zenious** [CS2103-AY1819S1-W17-3/main#109]
The bottom right corner of the GUI, reflect to the user the current storage location of MeetingBook. 

When user executes `filepath` command, the new filepath is not reflected as changes in the bottom right corner of the GUI.  Changes also not reflected as updates....

Before:
![image](https://user-images.githubusercontent.com/7553066/47259951-9f987180-d4e4-11e8-8946-ed04c47d4e19.png)

After:
![image](https://user-images.githubusercontent.com/7553066/47259954-ba6ae600-d4e4-11e8-841e-3e6b75cfc725.png)

**Comment by jeffreyooi** [comment]
@Zenious you fixing this or I fix since I'm responsible for GUI?

**Comment by Zenious** [comment]
Resolved #118 by @jeffreyooi
