### ISSUE TITLE
Invalid command usage message in LeaveCommand

### ISSUE THREAD

**Issue by Zenious** [CS2103-AY1819S1-W17-3/main#149]
![image](https://user-images.githubusercontent.com/7553066/47779345-dc116c00-dd33-11e8-8bd3-dadc4430f58a.png)

Parameters: n/NAME **g**/GROUP
Example: leave n/Derek Hardy **g**/GROUP_03

**Comment by Derek-Hardy** [comment]
This bug is fixed in the Pull Request #154
