### ISSUE TITLE
Unable to add more than 1 person to group

### ISSUE THREAD

**Issue by jeffreyooi** [CS2103-AY1819S1-W17-3/main#150]
Join command was not able to add more than one person to the group due to error in `AddressBook` that  when `target.clearMembers` is called, `editedGroup.setupMembers` will be cleared as well.

**Comment by Derek-Hardy** [comment]
Problem seems to occur at `updateGroup` call within `joinGroup` method in `AddressBook`.
Not sure why supposedly separate objects affect each other. The`updatePerson` counterpart seems to work fine.

**Comment by Derek-Hardy** [comment]
See whether the changes made in PR #154 address this problem.

**Comment by jeffreyooi** [comment]
Fixed in #154
