### ISSUE TITLE
Delete person does not remove itself from the group

### ISSUE THREAD

**Issue by jeffreyooi** [CS2103-AY1819S1-W17-3/main#152]
When a person is deleted, group still has a copy of the person's information

**Comment by Derek-Hardy** [comment]
A person is deleted through `removePerson` method in `AddressBook`. If the group remains a copy, it means `key.clearMembership()` is not working.

**Comment by Derek-Hardy** [comment]
See whether changes made in PR #154 address the problem.

**Comment by jeffreyooi** [comment]
I checked out your PR and tested this, however the group still contains a copy of the person's information after person is deleted

**Comment by jeffreyooi** [comment]
Fixed in #154
