### ISSUE TITLE
EnhancedMonth should be changed to DateUtil / MonthUtil

### ISSUE THREAD

**Issue by jeffreyooi** [CS2103-AY1819S1-W17-3/main#64]
Since EnhancedMonth is essentially for checking if the date is valid, it makes more sense to change it to util class (DateUtil / MonthUtil)

_Originally posted by @jeffreyooi in https://github.com/CS2103-AY1819S1-W17-3/main/pull/63#commitcomment-30832374_

**Comment by NyxF4ll** [comment]
Fixed in #107
